[project]
name = "PyCoco"
version = "0.1.0"
description = "COCO API in Python"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = ">=3.8"
setuptools = ">=18.0"
cython = ">=0.27.3"
matplotlib = ">=2.1.0"
pip = "*"
ipykernel = "*"
scikit-image = "*"
pytest = ">=8.4.1,<9"
numpy = ">=2.3.2,<3"

[build-dependencies]
setuptools = "*"

[tasks]
build = "python setup.py build_ext --inplace;rm -rf build"
test = "python pycocoEvalDemo.py"
tclean = "rm -rf pycocotools/*.c pycocotools/*.so"
